class_name Elements extends Resource

enum SYMBOL_LENGTH {
	INVALID,
	ONE,
	TWO
}

# Data from: https://github.com/Bowserinator/Periodic-Table-JSON/blob/master/periodic-table-lookup.json
const elements := {
	'Hydrogen' : {'symbol': 'H', 'number': 1, 'mass': 1.008, 'phase': 'Gas', 'electron_config': '1s1'},
	'Helium' : {'symbol': 'He', 'number': 2, 'mass': 4.003, 'phase': 'Gas', 'electron_config': '1s2'},
	'Lithium' : {'symbol': 'Li', 'number': 3, 'mass': 6.94, 'phase': 'Solid', 'electron_config': '[He] 2s1'},
	'Beryllium' : {'symbol': 'Be', 'number': 4, 'mass': 9.012, 'phase': 'Solid', 'electron_config': '[He] 2s2'},
	'Boron' : {'symbol': 'B', 'number': 5, 'mass': 10.81, 'phase': 'Solid', 'electron_config': '[He] 2s2 2p1'},
	'Carbon' : {'symbol': 'C', 'number': 6, 'mass': 12.011, 'phase': 'Solid', 'electron_config': '[He] 2s2 2p2'},
	'Nitrogen' : {'symbol': 'N', 'number': 7, 'mass': 14.007, 'phase': 'Gas', 'electron_config': '[He] 2s2 2p3'},
	'Oxygen' : {'symbol': 'O', 'number': 8, 'mass': 15.999, 'phase': 'Gas', 'electron_config': '[He] 2s2 2p4'},
	'Fluorine' : {'symbol': 'F', 'number': 9, 'mass': 18.998, 'phase': 'Gas', 'electron_config': '[He] 2s2 2p5'},
	'Neon' : {'symbol': 'Ne', 'number': 10, 'mass': 20.18, 'phase': 'Gas', 'electron_config': '[He] 2s2 2p6'},
	'Sodium' : {'symbol': 'Na', 'number': 11, 'mass': 22.99, 'phase': 'Solid', 'electron_config': '[Ne] 3s1'},
	'Magnesium' : {'symbol': 'Mg', 'number': 12, 'mass': 24.305, 'phase': 'Solid', 'electron_config': '[Ne] 3s2'},
	'Aluminium' : {'symbol': 'Al', 'number': 13, 'mass': 26.982, 'phase': 'Solid', 'electron_config': '[Ne] 3s2 3p1'},
	'Silicon' : {'symbol': 'Si', 'number': 14, 'mass': 28.085, 'phase': 'Solid', 'electron_config': '[Ne] 3s2 3p2'},
	'Phosphorus' : {'symbol': 'P', 'number': 15, 'mass': 30.974, 'phase': 'Solid', 'electron_config': '[Ne] 3s2 3p3'},
	'Sulfur' : {'symbol': 'S', 'number': 16, 'mass': 32.06, 'phase': 'Solid', 'electron_config': '[Ne] 3s2 3p4'},
	'Chlorine' : {'symbol': 'Cl', 'number': 17, 'mass': 35.45, 'phase': 'Gas', 'electron_config': '[Ne] 3s2 3p5'},
	'Argon' : {'symbol': 'Ar', 'number': 18, 'mass': 39.948, 'phase': 'Gas', 'electron_config': '[Ne] 3s2 3p6'},
	'Potassium' : {'symbol': 'K', 'number': 19, 'mass': 39.098, 'phase': 'Solid', 'electron_config': '[Ar] 4s1'},
	'Calcium' : {'symbol': 'Ca', 'number': 20, 'mass': 40.078, 'phase': 'Solid', 'electron_config': '[Ar] 4s2'},
	'Scandium' : {'symbol': 'Sc', 'number': 21, 'mass': 44.956, 'phase': 'Solid', 'electron_config': '[Ar] 3d1 4s2'},
	'Titanium' : {'symbol': 'Ti', 'number': 22, 'mass': 47.867, 'phase': 'Solid', 'electron_config': '[Ar] 3d2 4s2'},
	'Vanadium' : {'symbol': 'V', 'number': 23, 'mass': 50.942, 'phase': 'Solid', 'electron_config': '[Ar] 3d3 4s2'},
	'Chromium' : {'symbol': 'Cr', 'number': 24, 'mass': 51.996, 'phase': 'Solid', 'electron_config': '[Ar] 3d5 4s1'},
	'Manganese' : {'symbol': 'Mn', 'number': 25, 'mass': 54.938, 'phase': 'Solid', 'electron_config': '[Ar] 3d5 4s2'},
	'Iron' : {'symbol': 'Fe', 'number': 26, 'mass': 55.845, 'phase': 'Solid', 'electron_config': '[Ar] 3d6 4s2'},
	'Cobalt' : {'symbol': 'Co', 'number': 27, 'mass': 58.933, 'phase': 'Solid', 'electron_config': '[Ar] 3d7 4s2'},
	'Nickel' : {'symbol': 'Ni', 'number': 28, 'mass': 58.693, 'phase': 'Solid', 'electron_config': '[Ar] 3d8 4s2'},
	'Copper' : {'symbol': 'Cu', 'number': 29, 'mass': 63.546, 'phase': 'Solid', 'electron_config': '[Ar] 3d10 4s1'},
	'Zinc' : {'symbol': 'Zn', 'number': 30, 'mass': 65.382, 'phase': 'Solid', 'electron_config': '[Ar] 3d10 4s2'},
	'Gallium' : {'symbol': 'Ga', 'number': 31, 'mass': 69.723, 'phase': 'Solid', 'electron_config': '[Ar] 3d10 4s2 4p1'},
	'Germanium' : {'symbol': 'Ge', 'number': 32, 'mass': 72.631, 'phase': 'Solid', 'electron_config': '[Ar] 3d10 4s2 4p2'},
	'Arsenic' : {'symbol': 'As', 'number': 33, 'mass': 74.922, 'phase': 'Solid', 'electron_config': '[Ar] 3d10 4s2 4p3'},
	'Selenium' : {'symbol': 'Se', 'number': 34, 'mass': 78.972, 'phase': 'Solid', 'electron_config': '[Ar] 3d10 4s2 4p4'},
	'Bromine' : {'symbol': 'Br', 'number': 35, 'mass': 79.904, 'phase': 'Liquid', 'electron_config': '[Ar] 3d10 4s2 4p5'},
	'Krypton' : {'symbol': 'Kr', 'number': 36, 'mass': 83.798, 'phase': 'Gas', 'electron_config': '[Ar] 3d10 4s2 4p6'},
	'Rubidium' : {'symbol': 'Rb', 'number': 37, 'mass': 85.468, 'phase': 'Solid', 'electron_config': '[Kr] 5s1'},
	'Strontium' : {'symbol': 'Sr', 'number': 38, 'mass': 87.621, 'phase': 'Solid', 'electron_config': '[Kr] 5s2'},
	'Yttrium' : {'symbol': 'Y', 'number': 39, 'mass': 88.906, 'phase': 'Solid', 'electron_config': '[Kr] 4d1 5s2'},
	'Zirconium' : {'symbol': 'Zr', 'number': 40, 'mass': 91.224, 'phase': 'Solid', 'electron_config': '[Kr] 4d2 5s2'},
	'Niobium' : {'symbol': 'Nb', 'number': 41, 'mass': 92.906, 'phase': 'Solid', 'electron_config': '[Kr] 4d4 5s1'},
	'Molybdenum' : {'symbol': 'Mo', 'number': 42, 'mass': 95.951, 'phase': 'Solid', 'electron_config': '[Kr] 4d5 5s1'},
	'Technetium' : {'symbol': 'Tc', 'number': 43, 'mass': 98, 'phase': 'Solid', 'electron_config': '[Kr] 4d5 5s2'},
	'Ruthenium' : {'symbol': 'Ru', 'number': 44, 'mass': 101.072, 'phase': 'Solid', 'electron_config': '[Kr] 4d7 5s1'},
	'Rhodium' : {'symbol': 'Rh', 'number': 45, 'mass': 102.906, 'phase': 'Solid', 'electron_config': '[Kr] 4d8 5s1'},
	'Palladium' : {'symbol': 'Pd', 'number': 46, 'mass': 106.421, 'phase': 'Solid', 'electron_config': '[Kr] 4d10'},
	'Silver' : {'symbol': 'Ag', 'number': 47, 'mass': 107.868, 'phase': 'Solid', 'electron_config': '[Kr] 4d10 5s1'},
	'Cadmium' : {'symbol': 'Cd', 'number': 48, 'mass': 112.414, 'phase': 'Solid', 'electron_config': '[Kr] 4d10 5s2'},
	'Indium' : {'symbol': 'In', 'number': 49, 'mass': 114.818, 'phase': 'Solid', 'electron_config': '[Kr] 4d10 5s2 5p1'},
	'Tin' : {'symbol': 'Sn', 'number': 50, 'mass': 118.711, 'phase': 'Solid', 'electron_config': '[Kr] 4d10 5s2 5p2'},
	'Antimony' : {'symbol': 'Sb', 'number': 51, 'mass': 121.76, 'phase': 'Solid', 'electron_config': '[Kr] 4d10 5s2 5p3'},
	'Tellurium' : {'symbol': 'Te', 'number': 52, 'mass': 127.603, 'phase': 'Solid', 'electron_config': '[Kr] 4d10 5s2 5p4'},
	'Iodine' : {'symbol': 'I', 'number': 53, 'mass': 126.904, 'phase': 'Solid', 'electron_config': '[Kr] 4d10 5s2 5p5'},
	'Xenon' : {'symbol': 'Xe', 'number': 54, 'mass': 131.294, 'phase': 'Gas', 'electron_config': '[Kr] 4d10 5s2 5p6'},
	'Cesium' : {'symbol': 'Cs', 'number': 55, 'mass': 132.905, 'phase': 'Solid', 'electron_config': '[Xe] 6s1'},
	'Barium' : {'symbol': 'Ba', 'number': 56, 'mass': 137.328, 'phase': 'Solid', 'electron_config': '[Xe] 6s2'},
	'Lanthanum' : {'symbol': 'La', 'number': 57, 'mass': 138.905, 'phase': 'Solid', 'electron_config': '[Xe] 5d16s2'},
	'Cerium' : {'symbol': 'Ce', 'number': 58, 'mass': 140.116, 'phase': 'Solid', 'electron_config': '[Xe] 4f1 5d1 6s2'},
	'Praseodymium' : {'symbol': 'Pr', 'number': 59, 'mass': 140.908, 'phase': 'Solid', 'electron_config': '[Xe] 4f3 6s2'},
	'Neodymium' : {'symbol': 'Nd', 'number': 60, 'mass': 144.242, 'phase': 'Solid', 'electron_config': '[Xe] 4f4 6s2'},
	'Promethium' : {'symbol': 'Pm', 'number': 61, 'mass': 145, 'phase': 'Solid', 'electron_config': '[Xe] 4f5 6s2'},
	'Samarium' : {'symbol': 'Sm', 'number': 62, 'mass': 150.362, 'phase': 'Solid', 'electron_config': '[Xe] 4f6 6s2'},
	'Europium' : {'symbol': 'Eu', 'number': 63, 'mass': 151.964, 'phase': 'Solid', 'electron_config': '[Xe] 4f7 6s2'},
	'Gadolinium' : {'symbol': 'Gd', 'number': 64, 'mass': 157.253, 'phase': 'Solid', 'electron_config': '[Xe] 4f7 5d1 6s2'},
	'Terbium' : {'symbol': 'Tb', 'number': 65, 'mass': 158.925, 'phase': 'Solid', 'electron_config': '[Xe] 4f9 6s2'},
	'Dysprosium' : {'symbol': 'Dy', 'number': 66, 'mass': 162.5, 'phase': 'Solid', 'electron_config': '[Xe] 4f10 6s2'},
	'Holmium' : {'symbol': 'Ho', 'number': 67, 'mass': 164.93, 'phase': 'Solid', 'electron_config': '[Xe] 4f11 6s2'},
	'Erbium' : {'symbol': 'Er', 'number': 68, 'mass': 167.259, 'phase': 'Solid', 'electron_config': '[Xe] 4f12 6s2'},
	'Thulium' : {'symbol': 'Tm', 'number': 69, 'mass': 168.934, 'phase': 'Solid', 'electron_config': '[Xe] 4f13 6s2'},
	'Ytterbium' : {'symbol': 'Yb', 'number': 70, 'mass': 173.045, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 6s2'},
	'Lutetium' : {'symbol': 'Lu', 'number': 71, 'mass': 174.967, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d1 6s2'},
	'Hafnium' : {'symbol': 'Hf', 'number': 72, 'mass': 178.492, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d2 6s2'},
	'Tantalum' : {'symbol': 'Ta', 'number': 73, 'mass': 180.948, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d3 6s2'},
	'Tungsten' : {'symbol': 'W', 'number': 74, 'mass': 183.841, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d4 6s2'},
	'Rhenium' : {'symbol': 'Re', 'number': 75, 'mass': 186.207, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d5 6s2'},
	'Osmium' : {'symbol': 'Os', 'number': 76, 'mass': 190.233, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d6 6s2'},
	'Iridium' : {'symbol': 'Ir', 'number': 77, 'mass': 192.217, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d7 6s2'},
	'Platinum' : {'symbol': 'Pt', 'number': 78, 'mass': 195.085, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d9 6s1'},
	'Gold' : {'symbol': 'Au', 'number': 79, 'mass': 196.967, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d10 6s1'},
	'Mercury' : {'symbol': 'Hg', 'number': 80, 'mass': 200.592, 'phase': 'Liquid', 'electron_config': '[Xe] 4f14 5d10 6s2'},
	'Thallium' : {'symbol': 'Tl', 'number': 81, 'mass': 204.38, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d10 6s2 6p1'},
	'Lead' : {'symbol': 'Pb', 'number': 82, 'mass': 207.21, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d10 6s2 6p2'},
	'Bismuth' : {'symbol': 'Bi', 'number': 83, 'mass': 208.98, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d10 6s2 6p3'},
	'Polonium' : {'symbol': 'Po', 'number': 84, 'mass': 209, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d10 6s2 6p4'},
	'Astatine' : {'symbol': 'At', 'number': 85, 'mass': 210, 'phase': 'Solid', 'electron_config': '[Xe] 4f14 5d10 6s2 6p5'},
	'Radon' : {'symbol': 'Rn', 'number': 86, 'mass': 222, 'phase': 'Gas', 'electron_config': '[Xe] 4f14 5d10 6s2 6p6'},
	'Francium' : {'symbol': 'Fr', 'number': 87, 'mass': 223, 'phase': 'Solid', 'electron_config': '[Rn] 7s1'},
	'Radium' : {'symbol': 'Ra', 'number': 88, 'mass': 226, 'phase': 'Solid', 'electron_config': '[Rn] 7s2'},
	'Actinium' : {'symbol': 'Ac', 'number': 89, 'mass': 227, 'phase': 'Solid', 'electron_config': '[Rn] 6d1 7s2'},
	'Thorium' : {'symbol': 'Th', 'number': 90, 'mass': 232.038, 'phase': 'Solid', 'electron_config': '[Rn] 6d2 7s2'},
	'Protactinium' : {'symbol': 'Pa', 'number': 91, 'mass': 231.036, 'phase': 'Solid', 'electron_config': '[Rn] 5f2 6d1 7s2'},
	'Uranium' : {'symbol': 'U', 'number': 92, 'mass': 238.029, 'phase': 'Solid', 'electron_config': '[Rn] 5f3 6d1 7s2'},
	'Neptunium' : {'symbol': 'Np', 'number': 93, 'mass': 237, 'phase': 'Solid', 'electron_config': '[Rn] 5f4 6d1 7s2'},
	'Plutonium' : {'symbol': 'Pu', 'number': 94, 'mass': 244, 'phase': 'Solid', 'electron_config': '[Rn] 5f6 7s2'},
	'Americium' : {'symbol': 'Am', 'number': 95, 'mass': 243, 'phase': 'Solid', 'electron_config': '[Rn] 5f7 7s2'},
	'Curium' : {'symbol': 'Cm', 'number': 96, 'mass': 247, 'phase': 'Solid', 'electron_config': '[Rn] 5f7 6d1 7s2'},
	'Berkelium' : {'symbol': 'Bk', 'number': 97, 'mass': 247, 'phase': 'Solid', 'electron_config': '[Rn] 5f9 7s2'},
	'Californium' : {'symbol': 'Cf', 'number': 98, 'mass': 251, 'phase': 'Solid', 'electron_config': '[Rn] 5f10 7s2'},
	'Einsteinium' : {'symbol': 'Es', 'number': 99, 'mass': 252, 'phase': 'Solid', 'electron_config': '[Rn] 5f11 7s2'},
	'Fermium' : {'symbol': 'Fm', 'number': 100, 'mass': 257, 'phase': 'Solid', 'electron_config': '[Rn] 5f12 7s2'},
	'Mendelevium' : {'symbol': 'Md', 'number': 101, 'mass': 258, 'phase': 'Solid', 'electron_config': '[Rn] 5f13 7s2'},
	'Nobelium' : {'symbol': 'No', 'number': 102, 'mass': 259, 'phase': 'Solid', 'electron_config': '[Rn] 5f14 7s2'},
	'Lawrencium' : {'symbol': 'Lr', 'number': 103, 'mass': 266, 'phase': 'Solid', 'electron_config': '[Rn] 5f14 7s2 7p1'},
	'Rutherfordium' : {'symbol': 'Rf', 'number': 104, 'mass': 267, 'phase': 'Solid', 'electron_config': '[Rn] 5f14 6d2 7s2'},
	'Dubnium' : {'symbol': 'Db', 'number': 105, 'mass': 268, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d3 7s2'},
	'Seaborgium' : {'symbol': 'Sg', 'number': 106, 'mass': 269, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d4 7s2'},
	'Bohrium' : {'symbol': 'Bh', 'number': 107, 'mass': 270, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d5 7s2'},
	'Hassium' : {'symbol': 'Hs', 'number': 108, 'mass': 269, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d6 7s2'},
	'Meitnerium' : {'symbol': 'Mt', 'number': 109, 'mass': 278, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d7 7s2'},
	'Darmstadtium' : {'symbol': 'Ds', 'number': 110, 'mass': 281, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d9 7s1'},
	'Roentgenium' : {'symbol': 'Rg', 'number': 111, 'mass': 282, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d10 7s1'},
	'Copernicium' : {'symbol': 'Cn', 'number': 112, 'mass': 285, 'phase': 'Liquid', 'electron_config': '*[Rn] 5f14 6d10 7s2'},
	'Nihonium' : {'symbol': 'Nh', 'number': 113, 'mass': 286, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d10 7s2 7p1'},
	'Flerovium' : {'symbol': 'Fl', 'number': 114, 'mass': 289, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d10 7s2 7p2'},
	'Moscovium' : {'symbol': 'Mc', 'number': 115, 'mass': 289, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d10 7s2 7p3'},
	'Livermorium' : {'symbol': 'Lv', 'number': 116, 'mass': 293, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d10 7s2 7p4'},
	'Tennessine' : {'symbol': 'Ts', 'number': 117, 'mass': 294, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d10 7s2 7p5'},
	'Oganesson' : {'symbol': 'Og', 'number': 118, 'mass': 294, 'phase': 'Solid', 'electron_config': '*[Rn] 5f14 6d10 7s2 7p6'},
	'Ununennium' : {'symbol': 'Uue', 'number': 119, 'mass': 315, 'phase': 'Solid', 'electron_config': '*[Uuo] 8s1'},

}


const symbols := { 
	"H": "Hydrogen", "He": "Helium", "Li": "Lithium", "Be": "Beryllium", "B": "Boron", "C": "Carbon", "N": "Nitrogen", "O": "Oxygen", "F": "Fluorine", "Ne": "Neon", "Na": "Sodium", "Mg": "Magnesium", "Al": "Aluminium", "Si": "Silicon", "P": "Phosphorus", "S": "Sulfur", "Cl": "Chlorine", "Ar": "Argon", "K": "Potassium", "Ca": "Calcium", "Sc": "Scandium", "Ti": "Titanium", "V": "Vanadium", "Cr": "Chromium", "Mn": "Manganese", "Fe": "Iron", "Co": "Cobalt", "Ni": "Nickel", "Cu": "Copper", "Zn": "Zinc", "Ga": "Gallium", "Ge": "Germanium", "As": "Arsenic", "Se": "Selenium", "Br": "Bromine", "Kr": "Krypton", "Rb": "Rubidium", "Sr": "Strontium", "Y": "Yttrium", "Zr": "Zirconium", "Nb": "Niobium", "Mo": "Molybdenum", "Tc": "Technetium", "Ru": "Ruthenium", "Rh": "Rhodium", "Pd": "Palladium", "Ag": "Silver", "Cd": "Cadmium", "In": "Indium", "Sn": "Tin", "Sb": "Antimony", "Te": "Tellurium", "I": "Iodine", "Xe": "Xenon", "Cs": "Cesium", "Ba": "Barium", "La": "Lanthanum", "Ce": "Cerium", "Pr": "Praseodymium", "Nd": "Neodymium", "Pm": "Promethium", "Sm": "Samarium", "Eu": "Europium", "Gd": "Gadolinium", "Tb": "Terbium", "Dy": "Dysprosium", "Ho": "Holmium", "Er": "Erbium", "Tm": "Thulium", "Yb": "Ytterbium", "Lu": "Lutetium", "Hf": "Hafnium", "Ta": "Tantalum", "W": "Tungsten", "Re": "Rhenium", "Os": "Osmium", "Ir": "Iridium", "Pt": "Platinum", "Au": "Gold", "Hg": "Mercury", "Tl": "Thallium", "Pb": "Lead", "Bi": "Bismuth", "Po": "Polonium", "At": "Astatine", "Rn": "Radon", "Fr": "Francium", "Ra": "Radium", "Ac": "Actinium", "Th": "Thorium", "Pa": "Protactinium", "U": "Uranium", "Np": "Neptunium", "Pu": "Plutonium", "Am": "Americium", "Cm": "Curium", "Bk": "Berkelium", "Cf": "Californium", "Es": "Einsteinium", "Fm": "Fermium", "Md": "Mendelevium", "No": "Nobelium", "Lr": "Lawrencium", "Rf": "Rutherfordium", "Db": "Dubnium", "Sg": "Seaborgium", "Bh": "Bohrium", "Hs": "Hassium", "Mt": "Meitnerium", "Ds": "Darmstadtium", "Rg": "Roentgenium", "Cn": "Copernicium", "Nh": "Nihonium", "Fl": "Flerovium", "Mc": "Moscovium", "Lv": "Livermorium", "Ts": "Tennessine", "Og": "Oganesson", "Uue": "Ununennium" }


static func get_element(symbol: StringName) -> Dictionary:
	return elements[ symbols[symbol] ]  # do your own error-checking

static func is_element(symbol: StringName) -> bool:
	return symbols.has( symbol )

static func calculate_element_mass(symbol: StringName, count: float = 1) -> float:
	# e.g. mass = elements[ get_element("H") ].mass (=1.008) * 3 -> mass of 3 hydrogen atoms
	var mass : float = elements[ get_element( symbol ) ].mass * count
	return mass
